apiVersion: apps/v1
kind: Deployment
metadata:
  name: roshambo-deployment
  labels:
    app: roshambo-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: roshambo-app
  template:
    metadata:
      labels:
        app: roshambo-app
    spec:
      containers:
      - name: roshambo-container
        image: vyomlabs/roshambo:121
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: roshambo-service
spec:
  selector:
    app: roshambo-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
